import filmsMarkup from '../hbs-templates/films.hbs';
const filmsSection = document.querySelector('.films_title');

const mockData = [
  {
    adult: false,
    backdrop_path: '/jsz1HlxczSuTx0mDl2h0lxy36l.jpg',
    id: 616037,
    title: 'Thor: Love and Thunder',
    original_language: 'en',
    original_title: 'Thor: Love and Thunder',
    overview:
      'After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.',
    poster_path: '/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg',
    media_type: 'movie',
    genre_ids: [28, 12, 14],
    popularity: 5099.881,
    release_date: '2022-07-06',
    video: false,
    vote_average: 6.812,
    vote_count: 2798,
  },
  {
    adult: false,
    backdrop_path: '/lv4mA4jOnRSQCkmDYUyZ8ON43Dc.jpg',
    id: 532639,
    title: 'Pinocchio',
    original_language: 'en',
    original_title: 'Pinocchio',
    overview:
      'A live action and CGI retelling of the beloved tale of a wooden puppet who embarks on a thrilling adventure to become a real boy. Other characters include Geppetto, the woodcarver who builds and treats Pinocchio as if he were his real son; Jiminy Cricket, who serves as Pinocchio’s guide as well as his "conscience"; the Blue Fairy; "Honest" John; Sofia the Seagull and The Coachman.',
    poster_path: '/h32gl4a3QxQWNiNaR4Fc1uvLBkV.jpg',
    media_type: 'movie',
    genre_ids: [14, 12, 10751],
    popularity: 684.296,
    release_date: '2022-09-07',
    video: false,
    vote_average: 6.655,
    vote_count: 190,
  },
  {
    adult: false,
    backdrop_path: '/2k9tBql5GYH328Krj66tDT9LtFZ.jpg',
    id: 760741,
    title: 'Beast',
    original_language: 'en',
    original_title: 'Beast',
    overview:
      'A recently widowed man and his two teenage daughters travel to a game reserve in South Africa. However, their journey of healing soon turns into a fight for survival when a bloodthirsty lion starts to stalk them.',
    poster_path: '/xIGr7UHsKf0URWmyyd5qFMAq4d8.jpg',
    media_type: 'movie',
    genre_ids: [53, 27],
    popularity: 940.208,
    release_date: '2022-08-11',
    video: false,
    vote_average: 6.902,
    vote_count: 148,
  },
  {
    adult: false,
    backdrop_path: '/tsYoljpKxjTBHLuPGySHeloGkv5.jpg',
    id: 773975,
    title: 'End of the Road',
    original_language: 'en',
    original_title: 'End of the Road',
    overview:
      'Recently widowed mom Brenda fights to protect her family during a harrowing road trip when a murder and a missing bag of cash plunge them into danger.',
    poster_path: '/tLFIMuPWJHlTJ6TN8HCOiSD6SdA.jpg',
    media_type: 'movie',
    genre_ids: [53, 18, 80],
    popularity: 61.985,
    release_date: '2022-09-09',
    video: false,
    vote_average: 7.083,
    vote_count: 30,
  },
  {
    adult: false,
    backdrop_path: '/7Y3LdmsZukXhmwxtO0UF95BFBTt.jpg',
    id: 682507,
    title: 'Where the Crawdads Sing',
    original_language: 'en',
    original_title: 'Where the Crawdads Sing',
    overview:
      'Abandoned by her family, Kya raises herself all alone in the marshes outside of her small town. When her former boyfriend is found dead, Kya is instantly branded by the local townspeople and law enforcement as the prime suspect for his murder.',
    poster_path: '/n1el846gLDXfhOvrRCsyvaAOQWv.jpg',
    media_type: 'movie',
    genre_ids: [18, 9648, 53],
    popularity: 491.91,
    release_date: '2022-07-15',
    video: false,
    vote_average: 7.443,
    vote_count: 167,
  },
  {
    adult: false,
    backdrop_path: '/fY6n7AeEUnQuSKbfAF2Ftd3Z6sG.jpg',
    id: 911129,
    title: 'No Limit',
    original_language: 'fr',
    original_title: 'Sous emprise',
    overview:
      "Roxana Aubrey decides to drop her studies and escape her life in Paris for a free diving course in the south of France. She is quickly pulled into a life that reaches new depths brought by the weight of an ocean's descent.",
    poster_path: '/fUdeneiMUQkE1Yb3Qx7dML0HVf.jpg',
    media_type: 'movie',
    genre_ids: [18],
    popularity: 37.318,
    release_date: '2022-09-09',
    video: false,
    vote_average: 7.3,
    vote_count: 14,
  },
  {
    adult: false,
    backdrop_path: '/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg',
    id: 361743,
    title: 'Top Gun: Maverick',
    original_language: 'en',
    original_title: 'Top Gun: Maverick',
    overview:
      'After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.',
    poster_path: '/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
    media_type: 'movie',
    genre_ids: [28, 18],
    popularity: 1804.371,
    release_date: '2022-05-24',
    video: false,
    vote_average: 8.358,
    vote_count: 3567,
  },
  {
    adult: false,
    backdrop_path: '/PSBUyz5jXYqKr2OvLhQWmTbmSx.jpg',
    id: 1015606,
    title: "Obi-Wan Kenobi: A Jedi's Return",
    original_language: 'en',
    original_title: "Obi-Wan Kenobi: A Jedi's Return",
    overview:
      'A new documentary that showcases the making of the epic limited series. Features never-before-seen, behind-the-scenes footage, interviews and visits to the creature shop and props department.',
    poster_path: '/vQGgvXjoMZf8x1m3BHsMxVXPyck.jpg',
    media_type: 'movie',
    genre_ids: [99],
    popularity: 113.308,
    release_date: '2022-09-08',
    video: false,
    vote_average: 8.1,
    vote_count: 21,
  },
  {
    adult: false,
    backdrop_path: '/1DBDwevWS8OhiT3wqqlW7KGPd6m.jpg',
    id: 985939,
    title: 'Fall',
    original_language: 'en',
    original_title: 'Fall',
    overview:
      'For best friends Becky and Hunter, life is all about conquering fears and pushing limits. But after they climb 2,000 feet to the top of a remote, abandoned radio tower, they find themselves stranded with no way down. Now Becky and Hunter’s expert climbing skills will be put to the ultimate test as they desperately fight to survive the elements, a lack of supplies, and vertigo-inducing heights.',
    poster_path: '/9f5sIJEgvUpFv0ozfA6TurG4j22.jpg',
    media_type: 'movie',
    genre_ids: [53],
    popularity: 4808.091,
    release_date: '2022-08-11',
    video: false,
    vote_average: 7.411,
    vote_count: 332,
  },
  {
    adult: false,
    backdrop_path: '/9JGS0O9wAr7c56VwSEPyeKT6Xac.jpg',
    id: 507086,
    title: 'Jurassic World Dominion',
    original_language: 'en',
    original_title: 'Jurassic World Dominion',
    overview:
      'Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with history’s most fearsome creatures.',
    poster_path: '/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg',
    media_type: 'movie',
    genre_ids: [12, 28, 878],
    popularity: 1834.657,
    release_date: '2022-06-01',
    video: false,
    vote_average: 7.077,
    vote_count: 3255,
  },
  {
    adult: false,
    backdrop_path: '/lZSrpS0a0jPi5slt39UvnACNSa1.jpg',
    id: 821133,
    title: 'HollyBlood',
    original_language: 'es',
    original_title: 'HollyBlood',
    overview:
      "Javi, a perfectly ordinary teenager who doesn't suspect that his crush on Sara might be reciprocated. Through a string of misunderstandings, Sara comes to believe that Javi is in possession of supernatural powers.",
    poster_path: '/lcFw1XS35ULWwZde6iDI5m4BwuX.jpg',
    media_type: 'movie',
    genre_ids: [35, 10749, 27, 14],
    popularity: 8.663,
    release_date: '2022-07-22',
    video: false,
    vote_average: 7.182,
    vote_count: 11,
  },
  {
    adult: false,
    backdrop_path: '/xVbppM1xgbskOKgOuV8fbWBWHtt.jpg',
    id: 762504,
    title: 'Nope',
    original_language: 'en',
    original_title: 'Nope',
    overview:
      'Residents in a lonely gulch of inland California bear witness to an uncanny, chilling discovery.',
    poster_path: '/AcKVlWaNVVVFQwro3nLXqPljcYA.jpg',
    media_type: 'movie',
    genre_ids: [27, 9648, 878, 53],
    popularity: 1590.384,
    release_date: '2022-07-20',
    video: false,
    vote_average: 7.052,
    vote_count: 1316,
  },
  {
    adult: false,
    backdrop_path: '/nmGWzTLMXy9x7mKd8NKPLmHtWGa.jpg',
    id: 438148,
    title: 'Minions: The Rise of Gru',
    original_language: 'en',
    original_title: 'Minions: The Rise of Gru',
    overview:
      'A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them, with the backup of his followers, the Minions.',
    poster_path:
      'https://image.tmdb.org/t/p/w500/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg',
    media_type: 'movie',
    genre_ids: [16, 12, 35, 14],
    popularity: 1766.772,
    release_date: '2022-06-29',
    video: false,
    vote_average: 7.66,
    vote_count: 1874,
  },
  {
    adult: false,
    backdrop_path: '/kbqZrBDLMrTr6wZv2rtCb2VaGjS.jpg',
    id: 828613,
    title: 'About Fate',
    original_language: 'en',
    original_title: 'About Fate',
    overview:
      'When both of their engagement proposals are a bust, hopeless romantics Margot and Griffin find themselves together on New Year’s Eve after a bout of fateful events. Both believing in true love, they set out on a magical and comedic journey together, only to quickly realize that the love they’ve been searching for this whole time might be right in front of them.',
    poster_path: '/9GcpyEtyfOreHeX92QVv4r3habp.jpg',
    media_type: 'movie',
    genre_ids: [10749, 35],
    popularity: 40.578,
    release_date: '2022-09-08',
    video: false,
    vote_average: 5.8,
    vote_count: 5,
  },
  {
    adult: false,
    backdrop_path: '/fI8hv1IqWUIUjx4YRfl6TWhdqHW.jpg',
    id: 626872,
    title: 'Emergency Declaration',
    original_language: 'ko',
    original_title: '비상선언',
    overview:
      'While investigating a terroristic threat that goes viral online, Korean authorities discover that a suspect has recently boarded an international flight bound for the United States. When a healthy passenger on the same flight suddenly dies a gruesome death of unknown cause, panic erupts both in-flight and on the ground. With steadily decreasing fuel and international refusals to offer aid, the captain and crew will be forced to take unprecedented emergency measures in an attempt to save the lives of their passengers.',
    poster_path: '/h7kaQG5MbraSLibOuTpo0gtMxRz.jpg',
    media_type: 'movie',
    genre_ids: [18, 53],
    popularity: 61.732,
    release_date: '2022-08-03',
    video: false,
    vote_average: 7.188,
    vote_count: 16,
  },
  {
    adult: false,
    backdrop_path: '/vjnLXptqdxnpNJer5fWgj2OIGhL.jpg',
    id: 818397,
    title: 'Memory',
    original_language: 'en',
    original_title: 'Memory',
    overview:
      "Alex, an assassin-for-hire, finds that he's become a target after he refuses to complete a job for a dangerous criminal organization. With the crime syndicate and FBI in hot pursuit, Alex has the skills to stay ahead, except for one thing: he is struggling with severe memory loss, affecting his every move. Alex must question his every action and whom he can ultimately trust.",
    poster_path: '/4Q1n3TwieoULnuaztu9aFjqHDTI.jpg',
    media_type: 'movie',
    genre_ids: [28, 53, 80],
    popularity: 528.387,
    release_date: '2022-04-28',
    video: false,
    vote_average: 7.239,
    vote_count: 747,
  },
  {
    adult: false,
    backdrop_path: '/xyS0NgcQ2pbGWcwvSSu3xKEBhoO.jpg',
    id: 614934,
    title: 'Elvis',
    original_language: 'en',
    original_title: 'Elvis',
    overview:
      'The life story of Elvis Presley as seen through the complicated relationship with his enigmatic manager, Colonel Tom Parker.',
    poster_path: '/qBOKWqAFbveZ4ryjJJwbie6tXkQ.jpg',
    media_type: 'movie',
    genre_ids: [10402, 18, 36],
    popularity: 433.086,
    release_date: '2022-06-22',
    video: false,
    vote_average: 7.878,
    vote_count: 1398,
  },
  {
    adult: false,
    backdrop_path: '/iDeWAGnmloZ5Oz3bocDp4rSbUXd.jpg',
    id: 823625,
    title: 'Blacklight',
    original_language: 'en',
    original_title: 'Blacklight',
    overview:
      'Travis Block is a shadowy Government agent who specializes in removing operatives whose covers have been exposed. He then has to uncover a deadly conspiracy within his own ranks that reaches the highest echelons of power.',
    poster_path: '/bv9dy8mnwftdY2j6gG39gCfSFpV.jpg',
    media_type: 'movie',
    genre_ids: [28, 53],
    popularity: 323.799,
    release_date: '2022-02-10',
    video: false,
    vote_average: 6.327,
    vote_count: 615,
  },
  {
    adult: false,
    backdrop_path: '/ff4wDbIBCLCFOKN0B0ENhuIdNoo.jpg',
    id: 496331,
    title: 'Brahmāstra Part One: Shiva',
    original_language: 'hi',
    original_title: 'ब्रह्मास्त्र पहला भाग: शिवा',
    overview:
      'The story of Shiva – a young man on the brink of an epic love, with a girl named Isha. But their world is turned upside down when Shiva learns that he has a mysterious connection to the Brahmāstra... and a great power within him that he doesn’t understand just yet - the power of Fire.',
    poster_path: '/3O3oTeFERsfNHjwkMHQV26uMf7x.jpg',
    media_type: 'movie',
    genre_ids: [28, 12, 18, 14],
    popularity: 87.63,
    release_date: '2022-09-09',
    video: false,
    vote_average: 4.2,
    vote_count: 5,
  },
  {
    adult: false,
    backdrop_path: '/hYZ4a0JvPETdfgJJ9ZzyFufq8KQ.jpg',
    id: 629176,
    title: 'Samaritan',
    original_language: 'en',
    original_title: 'Samaritan',
    overview:
      'Thirteen year old Sam Cleary  suspects that his mysteriously reclusive neighbor Mr. Smith is actually the legendary vigilante Samaritan, who was reported dead 20 years ago. With crime on the rise and the city on the brink of chaos, Sam makes it his mission to coax his neighbor out of hiding to save the city from ruin.',
    poster_path: '/vwq5iboxYoaSpOmEQrhq9tHicq7.jpg',
    media_type: 'movie',
    genre_ids: [28, 18, 878],
    popularity: 4388.014,
    release_date: '2022-08-25',
    video: false,
    vote_average: 7.025,
    vote_count: 871,
  },
];

filmsSection.insertAdjacentHTML('beforeend', filmsMarkup({ mockData }));
