import './js/loader';
// import './sass/index.scss';
import './js/api-key';
import './js/api-top-films';
import './js/search';
import './js/pagination';
import './js/page-up';
import './js/array-of-genres';
import './js/fetchTopFilms';
import './js/footer-modal';
import './js/team-photo';
import './js/movie-modal-local-storage';
import './js/modal-open';
import './js/modal-close';
import './js/api-genres';
