import './js/loader';
import './sass/index.scss';
import './js/api-key';
import './js/buttons';
import './js/local-storage';
// import './js/pagination';
import './js/page-up';
import './js/array-of-genres';
import './js/footer-modal';
import './js/team-photo';
import './js/movie-modal';
import './js/modal-open';
import './js/modal-close';
